version: "3.7"


services: 
    nginx:
        image: nginx:1.17.9
        depends_on: 
            - php
        container_name: nginx
        volumes: 
            - ./nginx/html:/usr/share/nginx/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./phpinfo:/opt/demo
        restart: always
        networks: 
            - lnmp
        ports: 
            - "8899:80"
            - "8898:81"
            - "8897:8383"
    php:
        build: 
            context: ./php
            dockerfile: Dockerfile
        depends_on: 
            - mysql
            - redis
            - elasticsearch
        restart: always
        container_name: php
        networks: 
            - lnmp
            - mysql_netword
            - php_redis
            - elastic
        ports: 
            - "9000:9000"
        volumes: 
            - ./phpinfo:/opt/demo
    mysql:
        image: mysql:8.0
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
           MYSQL_ROOT_PASSWORD: root
        volumes: 
            - ./mysql/my.cnf:/etc/my.cnf
            - mysql_data:/var/lib/mysql
        networks: 
           - mysql_netword
        ports: 
            - "3306"
    redis:
        image: redis
        container_name: redis
        restart: always
        volumes: 
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        command: ["redis-server","/usr/local/etc/redis/redis.conf","--daemonize no","--appendonly yes"]
        ports: 
            - "6379"
        networks: 
            - php_redis
    elastic:
        build: ./elastic
        container_name: elastic
        environment:
            - node.name=docker_elasitc
            - cluster.name=es-docker-cluster
            - http.cors.enabled=true
            - http.cors.allow-origin="*"
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - discovery.seed_hosts=elastic
            - cluster.initial_master_nodes=docker_elasitc
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
             - elastic_data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - elastic
    kibana:
        image: docker.elastic.co/kibana/kibana:7.6.2@sha256:e8f3743e404462709663422056db2d5076a7a6bd6024f64aea1599b3014c63be
        container_name: kibana
        volumes: 
            - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
            - kibana_data:/usr/share/kibana/data
        depends_on: 
          - elastic
        networks: 
            - elastic
        ports:
            - "5601:5601"


            
networks: 
    lnmp:
      driver: bridge
    mysql_netword:
        driver: bridge
    php_redis:
        driver: bridge
    elastic:
        driver: bridge
volumes: 
   mysql_data:
   elastic_data:

